module.exports = {
  content: ['./components/**/*.{js,ts,jsx,tsx}'],
  safelist: [
    'shadow-deathknight',
    'shadow-demonhunter',
    'shadow-druid',
    'shadow-hunter',
    'shadow-mage',
    'shadow-monk',
    'shadow-paladin',
    'shadow-priest',
    'shadow-rogue',
    'shadow-shaman',
    'shadow-warlock',
    'shadow-warrior',
    'shadow-evoker',

    'border-deathknight',
    'border-demonhunter',
    'border-druid',
    'border-hunter',
    'border-mage',
    'border-monk',
    'border-paladin',
    'border-priest',
    'border-rogue',
    'border-shaman',
    'border-warlock',
    'border-warrior',
    'border-evoker',
  ],
  theme: {
    colors: {
      black: '#000',
      deathknight: '#C41E3A',
      demonhunter: '#A330C9',
      evoker: '33937F',
      druid: '#FF7D0A',
      hunter: '#A9D271',
      mage: '#40C7EB',
      monk: '#00FF98',
      paladin: '#F58CBA',
      priest: '#FFFFFF',
      rogue: '#FFF569',
      shaman: '#0070DE',
      warlock: '#8787ED',
      warrior: '#C79C6E',
    },
    extend: {
      animation: {
        'spin-slow': 'spin 3s linear infinite',
        fadein: 'fadein 0.25s ease-in',
        loader: 'loader 0.35s ease-in',
      },
      keyframes: {
        fadein: {
          '0%': { opacity: 0 },
          '100%': { opacity: 1 },
        },
        loader: {
          '0%': { opacity: 0 },
          '30%': { opacity: 0 },
          '100%': { opacity: 1 },
        },
      },
    },
  },
  plugins: [require('@tailwindcss/typography'), require('daisyui')],
  daisyui: {
    themes: ['halloween'],
  },
};
