service: gcp-wowarenalogs

provider:
  name: google
  stage: prod
  runtime: nodejs20
  region: us-central1
  project: wowarenalogs-public-dev
  credentials: wowarenalogs-public-dev.json

plugins:
  - serverless-google-cloudfunctions

package:
  include:
    - 'index.js'

functions:
  writeMatchStub:
    memorySize: 1024
    handler: writeMatchStubHandler
    environment:
      ENV_MATCH_STUBS_FIRESTORE: match-stubs-prod
      ENV_LOG_FILES_BUCKET: ${self:provider.project}-log-files-prod
      ENV_GCP_PROJECT: ${self:provider.project}
      ENV_SERVICE_NAME: ${self:service}
      ENV_SQL_URL: ${env:ENV_SQL_URL}
    events:
      - event:
          eventType: google.storage.object.finalize
          resource: projects/wowarenalogs/buckets/${self:provider.project}-log-files-prod
          failurePolicy:
            retry: {}
