name: release-app
on:
  push:
    branches:
      - release/wowarenalogs/app
jobs:
  build_on_win:
    runs-on: windows-latest
    env:
      CI: false
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      CSC_LINK: ${{ secrets.CSC_LINK }}
      CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
    steps:
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: gcloud auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}
      - name: setup gcloud
        uses: google-github-actions/setup-gcloud@v1
        env:
          CLOUDSDK_PYTHON: ${{env.pythonLocation}}\python.exe
      - name: checkout
        uses: actions/checkout@v3
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: install windows build tools
        run: npm i -g windows-build-tools@4.0.0
      - name: install node-gyp
        run: npm i -g node-gyp@latest
      - name: update path variables
        run: set 'path=%path%;C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Current\Bin'
      - name: clean npm cache
        run: npm cache clean -f
      - name: install dependencies
        run: npm ci
      - name: build for windows
        run: npm run publish:app:windows
      - name: upload to google cloud storage
        working-directory: ./dist
        env:
          CLOUDSDK_PYTHON: ${{env.pythonLocation}}\python.exe
        run: gsutil cp *.exe gs://download.wowarenalogs.com/desktop-client/
      - name: rename exe to latest-windows.exe
        working-directory: ./dist
        run: Rename-Item -Path $(Get-ChildItem .\ -filter *.exe -Name) -NewName latest-windows.exe
        shell: powershell
      - name: upload latest-windows.exe
        working-directory: ./dist
        env:
          CLOUDSDK_PYTHON: ${{env.pythonLocation}}\python.exe
        run: gsutil cp latest-windows.exe gs://download.wowarenalogs.com/desktop-client/
  build_on_mac:
    if: "contains(github.event.commits[0].message, '[build-for-mac]')"
    runs-on: macos-latest
    env:
      CI: false
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      CSC_LINK: ${{ secrets.CSC_LINK }}
      CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
      APPLE_ID: ${{ secrets.APPLE_ID }}
      APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
      APPLE_APP_SPECIFIC_PASSWORD: ${{ secrets.APPLE_PASSWORD }}
    steps:
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: gcloud auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}
      - name: setup gcloud
        uses: google-github-actions/setup-gcloud@v1
      - name: checkout
        uses: actions/checkout@v3
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: update node_canvas deps
        run: brew install pkg-config cairo pango libpng jpeg giflib librsvg
      - name: install node-gyp
        run: npm i -g node-gyp@latest
      - name: clean npm cache
        run: npm cache clean -f
      - name: install dependencies
        run: npm ci
      - name: install dmg-license
        run: npm i dmg-license
      - name: build for mac
        run: npm run publish:app:mac
      - name: upload to google cloud storage
        working-directory: ./dist
        run: gsutil cp *.dmg gs://download.wowarenalogs.com/desktop-client/
      - name: create latest-mac.zip
        working-directory: ./dist
        run: zip latest-mac.zip *.dmg
      - name: upload latest-mac.zip
        working-directory: ./dist
        run: gsutil cp latest-mac.zip gs://download.wowarenalogs.com/desktop-client/
  build_on_linux:
    runs-on: ubuntu-latest
    env:
      CI: false
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: gcloud auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}
      - name: setup gcloud
        uses: google-github-actions/setup-gcloud@v1
      - name: checkout
        uses: actions/checkout@v3
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: install node-gyp
        run: npm i -g node-gyp@latest
      - name: clean npm cache
        run: npm cache clean -f
      - name: install dependencies
        run: npm ci
      - name: build for linux
        run: npm run publish:app:linux
      - name: upload to google cloud storage
        working-directory: ./dist
        run: gsutil cp *.AppImage gs://download.wowarenalogs.com/desktop-client/
      - name: create latest-linux.zip
        working-directory: ./dist
        run: zip latest-linux.zip *.AppImage
      - name: upload latest-linux.zip
        working-directory: ./dist
        run: gsutil cp latest-linux.zip gs://download.wowarenalogs.com/desktop-client/
